name: publish

on:
  release:
    types: [released]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn prepack
      - run: npm publish
      - run: yarn postpack
